### ISSUE TITLE
Workflows behaves like they are being paused/resumed everytime DSC runs a consistency check

### ISSUE THREAD

**Issue by AWahlqvist** [bgelens/HybridRunbookWorkerDsc#4]
First of all, thanks a lot for creating this module, it has worked flawlessly for us for months, up until yesterday evening when we noticed some jobs were behaving really weird.

Basically it was like they were being suspended/resumed every time DSC ran (the jobs never changed status though, but I could tell from the job output that they were suddenly running from an earlier checkpoint). On some long running jobs (more than the DSC interval between checkpoints), they never finished.

After some digging I noticed that every time DSC ran, the Microsoft Monitoring Agent service was restarted. I also noticed four events under the "Operations Manager" log with Event ID 4502 similar to this (just different file paths):
"A module of type "Microsoft.EnterpriseManagement.HealthService.AzureAutomation.HybridAgent" reported an exception Microsoft.EnterpriseManagement.HealthService.ModuleException: Failed to copy file. Copy operation failed : C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.2.12024.0\HybridRegistration\AgentService.Shared.dll.
 Error : System.IO.IOException: The process cannot access the file 'C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.2.12024.0\HybridRegistration\AgentService.Shared.dll' because it is being used by another process."

And the restart events of the MMA service under the system eventlog (eventid 7036):
The Microsoft Monitoring Agent service entered the stopped state.
The Microsoft Monitoring Agent service entered the running state.

When looking in the Microsoft-SMA log I could also see that it actually removed the sandbox and created a new one for the job.

My current workaround has been to temporarily remove the HybridRunbookWorker-resource from our DSC config, after that, the problems went away.

I noticed the hybrid workers had updated their Hybrid Worker modules through OMS, so I guess that is related (and why the copy attempts above kept happening).

This started to happen yesterday evening on hybrid workers in more than 5 different automation accounts, which also seem to point in the direction of a central update of the module being pushed to the hybrid workers.

Hybrid Workers run WS2K16 as their OS.

I tried removing them as hybrid workers and let DSC onboard them again, also tried deleting the hybrid worker module and let OMS push them out again, problem still occurred on every consistency check.

Might be something unique to us I guess, but still wanted to let you know!

Thanks again!

//Anders

**Comment by bgelens** [comment]
Thanks for reporting, I'll start investigation asap

**Comment by bgelens** [comment]
@AWahlqvist I identified the issue. The registry paths have changed. I will update the HybridRunbookWorkerDsc Module as the HybridRunbookWorker will be discontinued as soon as Microsoft accepts this module into the DSC Resource Kit. In the mean time, I will publish this module (once adjusted) to the PSGallery and will unlist the old one.

**Comment by AWahlqvist** [comment]
Awesome, I wish I could get support as quick and great as this from some of the paid services I use :-) Thanks a lot @bgelens !
