### ISSUE TITLE
Issues starting up on my VMSS nodes.  Unclear error message.

### ISSUE THREAD

**Issue by PolyphonyRequiem** [bgelens/HybridRunbookWorkerDsc#5]
Getting a pretty much useless error message trying to use this to join my VMSS nodes to an automation account's worker groups.

Resource-
HybridRunbookWorker Onboard {
            Ensure    = 'Present'
            Endpoint  = $AAVAR_AutomationEndpoint
            Token     = $AAVAR_AutomationCredential
            GroupName = $Node.NodeName
            DependsOn = '[WaitForHybridRegistrationModule]ModuleWait'
        }

The only thing I can think is that my credential or endpoint is somehow wrong, but I double checked the variables.

{
    "Exception":  {
                      "Message":  "The PowerShell DSC resource \u0027[HybridRunbookWorker]Onboard\u0027 with SourceInfo \u0027::87::9::HybridRunbookWorker\u0027 threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.",
                      "Data":  {

                               },
                      "InnerException":  null,
                      "TargetSite":  null,
                      "StackTrace":  null,
                      "HelpLink":  null,
                      "Source":  null,
                      "HResult":  -2146233079
                  },
    "TargetObject":  null,
    "CategoryInfo":  {
                         "Category":  7,
                         "Activity":  "",
                         "Reason":  "InvalidOperationException",
                         "TargetName":  "",
                         "TargetType":  ""
                     },
    "FullyQualifiedErrorId":  "NonTerminatingErrorFromProvider",
    "ErrorDetails":  null,
    "InvocationInfo":  null,
    "ScriptStackTrace":  null,
    "PipelineIterationInfo":  [

                              ]
}

**Comment by bgelens** [comment]
Could you share the entire dsc configuration script?

I tested a deployment on standard VM today and the [example](https://github.com/bgelens/HybridRunbookWorkerDsc/blob/dev/Examples/FullExamples/1-FullConfig.ps1) is still working for that. Did you look at this sample?

Not sure why you would want to do this in VMMS. How would you handle scale-down?

**Comment by bgelens** [comment]
Closing issue as there was no response for over a month.
